/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'araman' at '22/6/15 10:32 PM' with Gradle 2.4
 *
 * @author araman, @date 22/6/15 10:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
